#!/usr/bin/env python3
"""
Clean Confluence-exported markdown files for Jekyll integration.
Removes Confluence-specific HTML divs, spans, and formatting.
Extracts clean content and creates Jekyll front matter.
"""

import re
import os
from pathlib import Path

def extract_title(content):
    """Extract the page title from Confluence markdown."""
    # Look for the title in the heading
    title_match = re.search(r'#\s*\[.*?:\s*([^\]]+)\]', content)
    if title_match:
        return title_match.group(1).strip()

    # Fallback: look for first # heading
    heading_match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
    if heading_match:
        return heading_match.group(1).strip()

    return "Untitled"

def extract_metadata(content):
    """Extract author and date metadata from Confluence format."""
    author = None
    date = None

    # Extract author
    author_match = re.search(r'Created by \[\s*([^\]]+)\]', content)
    if author_match:
        author = author_match.group(1).strip()

    # Extract last updated date
    date_match = re.search(r'last updated.*?on\s+([A-Z][a-z]+\s+\d+,\s+\d{4})', content)
    if date_match:
        date = date_match.group(1).strip()

    return author, date

def clean_markdown_content(content):
    """Remove Confluence-specific formatting and extract clean markdown."""

    # Remove all ::: div markers and their attributes
    content = re.sub(r'^:{3,}.*?{[^}]*}.*$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^:{3,}.*$', '', content, flags=re.MULTILINE)

    # Remove breadcrumb sections (numbered lists at the top)
    content = re.sub(r'^\d+\.\s+\[.*?\]\(.*?\)\s*$', '', content, flags=re.MULTILINE)

    # Remove page metadata div content (already extracted)
    content = re.sub(r'Created by.*?last updated.*?(?:on|by).*?\d{4}', '', content, flags=re.MULTILINE)

    # Remove the Confluence title heading (we'll use Jekyll front matter)
    content = re.sub(r'^#\s*\[.*?CALM Microscopy Wiki\s*:\s*[^\]]+\].*?{.*?}.*$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^#\s*!\[.*?\].*?{.*?}\s*\[.*?CALM Microscopy Wiki\s*:\s*[^\]]+\].*?{.*?}.*$', '', content, flags=re.MULTILINE)

    # Remove image tags with Confluence attributes
    content = re.sub(r'!\[.*?\]\(.*?\){[^}]*}', '', content)

    # Clean up Confluence-style links with attributes
    # Convert [text](link.html){attributes} to [text](link)
    content = re.sub(r'\]\(([^)]+\.html)\){[^}]*}', r'](\1)', content)

    # Remove attachment links (we'll handle these separately)
    content = re.sub(r'\[([^\]]+)\]\(attachments/[^)]+\){[^}]*}', r'\1 (attachment)', content)

    # Clean up nested bracket artifacts like [[text]]
    content = re.sub(r'\[\[([^\]]+)\]\]', r'\1', content)

    # Clean up span/class remnants like ]{.class style="..."}
    content = re.sub(r'\]{\.[\w\s.-]+(?:\s+\.[\w\s.-]+)*\s+style="[^"]*"}', '', content)
    content = re.sub(r'\]{\.[\w\s.-]+(?:\s+\.[\w\s.-]+)*}', '', content)

    # Clean up span tags with classes
    content = re.sub(r'\[([^\]]+)\]{\.[\w\s-]+}', r'\1', content)
    content = re.sub(r'\[([^\]]+)\]{\.[\w\s-]+\s+style="[^"]*"}', r'\1', content)

    # Remove inline style attributes
    content = re.sub(r'{style="[^"]*"}', '', content)
    content = re.sub(r'\]\{style="[^"]*"\}', ']', content)

    # Remove other attribute blocks
    content = re.sub(r'{[^}]*role="[^"]*"[^}]*}', '', content)
    content = re.sub(r'{\.[\w-]+(?:\s+\.[\w-]+)*}', '', content)
    content = re.sub(r'{#[\w-]+}', '', content)  # Remove id attributes

    # Clean up heading anchors like {#SomeId-SomeText}
    content = re.sub(r'\s*{#[^}]+}', '', content)

    # Remove .wikilink class remnants
    content = re.sub(r'\]{\.wikilink\d*}', ']', content)

    # Clean up external-link class
    content = re.sub(r'\]{\.external-link\s+rel="nofollow"}', ']', content)

    # Clean up footer
    content = re.sub(r'Document generated by Confluence.*', '', content, flags=re.DOTALL)
    content = re.sub(r'\[Atlassian\]\(https://www\.atlassian\.com/\)', '', content)

    # Remove excessive blank lines (more than 2)
    content = re.sub(r'\n{3,}', '\n\n', content)

    # Clean up stray brackets and parentheses from cleanup
    content = re.sub(r'\[\s*\]', '', content)

    # Strip leading/trailing whitespace
    content = content.strip()

    return content

def create_jekyll_front_matter(title, author=None, date=None, category=None):
    """Create Jekyll front matter."""
    front_matter = "---\n"
    front_matter += f"layout: default\n"
    front_matter += f"title: {title}\n"

    if category:
        front_matter += f"category: {category}\n"

    if author:
        front_matter += f"author: {author}\n"

    if date:
        front_matter += f"date: {date}\n"

    front_matter += "---\n\n"
    return front_matter

def process_markdown_file(input_path, output_path, category=None):
    """Process a single markdown file.

    Args:
        input_path: Path to input markdown file
        output_path: Path to output cleaned file
        category: Optional category for Jekyll front matter

    Returns:
        Extracted title from the file
    """
    print(f"Processing: {input_path.name}")

    try:
        # Read the original file
        with open(input_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Extract metadata
        title = extract_title(content)
        author, date = extract_metadata(content)

        # Clean the content
        clean_content = clean_markdown_content(content)

        # Create front matter
        front_matter = create_jekyll_front_matter(title, author, date, category)

        # Combine front matter and content
        final_content = front_matter + clean_content

        # Write to output file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(final_content)

        return title
    except Exception as e:
        print(f"  [ERROR] Failed to process {input_path.name}: {e}")
        return None

def main():
    """Main processing function."""
    # Paths
    input_dir = Path("pandoc-folder/CMW/Markdown")
    output_dir = Path("wiki/pages")

    # Validate input directory exists
    if not input_dir.exists():
        print(f"[ERROR] Input directory not found: {input_dir}")
        return

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Process all markdown files
    processed_files = []
    error_count = 0

    for md_file in sorted(input_dir.glob("*.md")):
        output_file = output_dir / md_file.name
        title = process_markdown_file(md_file, output_file)
        if title:
            processed_files.append((md_file.name, title))
        else:
            error_count += 1

    print(f"\n[OK] Processed {len(processed_files)} files")
    if error_count > 0:
        print(f"[WARN] {error_count} files had errors")
    print(f"[OK] Output directory: {output_dir}")

    # Save a mapping file for categorization
    mapping_file = output_dir / "_file_mapping.txt"
    with open(mapping_file, 'w', encoding='utf-8') as f:
        f.write("# File mapping: filename -> title\n")
        for filename, title in processed_files:
            f.write(f"{filename}\t{title}\n")

    print(f"[OK] Created mapping file: {mapping_file}")

if __name__ == "__main__":
    main()
